name: Prune Old Container Images
on:
  schedule:
    - cron: '36 10 * * *'
  push:
    branches:
      - latest
jobs:
  prune-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: cmspam
          container: incus-docker
          dry-run: false # Dry-run first, then change to `false`
          keep-younger-than: 7 # days
          keep-last: 2
          prune-untagged: true
